server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  data:
    mongodb:
      uri: mongodb+srv://bootcamp:eo4IaJNIbjk4f8ls@cluster0.hlzdcri.mongodb.net/transaction?retryWrites=true&w=majority
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/banking-nttdata-bootcamp/deposit
  application:
    name: deposit

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${localhost:${random.value}}
    service-url:
      default-zone: http://dknttdata-eureka-server:8761/eureka
    prefer-ip-address: true

springdoc:
  packagesToScan: com.nttdata.bootcamp

resilience4j.circuitbreaker:
  instances:
    deposit:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 2s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10