server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  data:
    mongodb:
      #uri: mongodb+srv://bootcamp:eo4IaJNIbjk4f8ls@cluster0.hlzdcri.mongodb.net/transaction?retryWrites=true&w=majority
      uri: mongodb+srv://jlodarsantamaria_db_user:nT0dlTcHLqCVvV6p@clusterodar.topeczm.mongodb.net/transaction?appName=clusterodar
  cloud:
    config:
      server:
        git:
          default-label: master
          #uri: https://github.com/banking-nttdata-bootcamp/payment
          uri: https://github.com/jlodars/payment
  application:
    name: payment

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${localhost:${random.value}}
    service-url:
      default-zone: http://localhost:8761/eureka
    prefer-ip-address: true

springdoc:
  packagesToScan: com.nttdata.bootcamp

resilience4j.circuitbreaker:
  instances:
    payment:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 2s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10